name: Compile and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: ${{ matrix.compiler }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            compiler: MSVC
            arch: "x64"
            cc: ""
            cxx: ""
          - os: ubuntu-latest
            compiler: GCC
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            compiler: Clang
            cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Install Compiler (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ clang ninja-build

      - name: Configure CMake
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == windows-* ]]; then
            cmake -B build -G "Ninja" -A ${{ matrix.arch }} \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DSBS_BUILD_TESTS=On
          else
            cmake -B build -G "Ninja" \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DSBS_BUILD_TESTS=On \
            ${{ matrix.cc != '' && format('-DCMAKE_C_COMPILER={0}', matrix.cc) || '' }} \
            ${{ matrix.cxx != '' && format('-DCMAKE_CXX_COMPILER={0}', matrix.cxx) || '' }}
          fi

      - name: Compile
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure